package ar.edu.itba.cripto.steganography;

import java.io.IOException;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;

import ar.edu.itba.cripto.bmp.BMPFile;
import ar.edu.itba.cripto.utils.Config;

public class SteganographyEngine {

    private static final int SEED_RANGE = 65536;
    public static final int LSB_BITS_NON_K8 = 4;

    private final Config config;
    private final BMPFile secretImage; // null during recovery
    private final List<BMPFile> shadowImages;

    public SteganographyEngine(Config config, BMPFile secretImage, List<BMPFile> shadowImages) {
        this.config = config;
        this.secretImage = secretImage;
        this.shadowImages = shadowImages;
    }

    public void distribute() throws IOException {
        int k = config.getK();
        int n = shadowImages.size();

        int seed = new Random().nextInt(SEED_RANGE);

        int[] pixels = secretImage.getDataAsIntArray();
        PermutationTable pt = new PermutationTable(seed, pixels.length);
        int[] permutedData = pt.apply(pixels);

        int sections = permutedData.length / k;
        int[][] shadowPixels = buildShadowPixels(permutedData, n, k, sections);

        for (int i = 0; i < n; i++) {
            BMPFile carrier = shadowImages.get(i);
            int shadowNumber = i + 1;

            int bits = (k == 8) ? 1 : LSB_BITS_NON_K8;
            LSB.hide(carrier, shadowPixels[i], shadowNumber, seed, bits);
            carrier.save(carrier.getPath());
        }

        System.out.println("Distributed secret into " + n + " shadow images (k=" + k + ").");
    }

    public void recover() throws IOException {
        int k = config.getK();
        List<BMPFile> carriers = shadowImages;

        int seed = carriers.getFirst().getSeed();

        int[] xs = new int[k];
        for (int i = 0; i < k; i++) {
            xs[i] = carriers.get(i).getShadowNumber();
        }

        for (int i = 1; i < k; i++) {
            if (carriers.get(i).getSeed() != seed) {
                throw new IllegalArgumentException(
                        "Carriers have inconsistent seeds. " +
                        "All k carriers must come from the same distribution run.");
            }
        }

        Set<Integer> seen = new HashSet<>();
        for (int i = 0; i < k; i++) {
            if (xs[i] <= 0) {
                throw new IllegalArgumentException(
                        "Invalid shadow number " + xs[i] + " in carrier '" +
                        carriers.get(i).getPath().getFileName() + "'. " +
                        "Make sure all carriers were generated by this program.");
            }
            if (!seen.add(xs[i])) {
                throw new IllegalArgumentException(
                        "Duplicate shadow number " + xs[i] + " detected. " +
                        "All k carriers must be different shadows from the same distribution.");
            }
        }

        int sections;
        int[][] shadowValues = new int[k][];

        if (k == 8) {
            sections = carriers.get(0).getData().length / 8;
            for (int i = 0; i < k; i++) {
                shadowValues[i] = LSB.extract(carriers.get(i), sections, 1);
            }
        } else {
            sections = carriers.get(0).getData().length * LSB_BITS_NON_K8 / 8;
            for (int i = 0; i < k; i++) {
                shadowValues[i] = LSB.extract(carriers.get(i), sections, LSB_BITS_NON_K8);
            }
        }

        // Recover permuted pixels via Gauss-Jordan mod 257
        int totalPixels = sections * k;
        int[] permutedPixels = new int[totalPixels];

        for (int j = 0; j < sections; j++) {
            int[] ys = new int[k];
            for (int i = 0; i < k; i++) {
                ys[i] = shadowValues[i][j];
            }
            int[] coefficients = WuLoPolynomial.recoverCoefficients(xs, ys);
            System.arraycopy(coefficients, 0, permutedPixels, j * k, k);
        }

        // Invert permutation (XOR is self-inverse with same table)
        PermutationTable pt = new PermutationTable(seed, totalPixels);
        int[] recoveredPixels = pt.apply(permutedPixels);

        byte[] pixelData = new byte[totalPixels];
        for (int i = 0; i < totalPixels; i++) {
            pixelData[i] = (byte) recoveredPixels[i];
        }

        // Determine output dimensions
        BMPFile carrier0 = carriers.get(0);
        int outHeight = carrier0.getHeight();
        int outWidth  = (k == 8) ? carrier0.getWidth() : totalPixels / outHeight;

        BMPFile output = BMPFile.createOutput(carrier0, outWidth, outHeight, pixelData);
        output.save(Paths.get(config.getSecretImagePath()));

        System.out.println("Secret image recovered: " + config.getSecretImagePath());
    }

    private int[][] buildShadowPixels(int[] permutedData, int n, int k, int sections) {
        int[][] shadowPixels = new int[n][sections];
        for (int j = 0; j < sections; j++) {
            int[] coefficients = Arrays.copyOfRange(permutedData, j * k, j * k + k);
            WuLoPolynomial shamir = new WuLoPolynomial(coefficients);
            int[] shares = shamir.computeShares(n);
            for (int i = 0; i < n; i++) {
                shadowPixels[i][j] = shares[i];
            }
        }
        return shadowPixels;
    }
}
